#:kivy 1.11.1

<Compass>:
    BoxLayout:
		orientation: "vertical"
		spacing: dp(10)
        CustomActionBar:
            CustomButton:
				size_hint: None, 1
				on_press: root.dismiss()
				canvas:
					Rectangle:
						source: "data/back.png"
						pos: self.pos
						size: dp(32), dp(32)
				size: dp(32), dp(32)
            CustomLabel:
                text: "Compass"
        BoxLayout:
            BlackLabel:
                text: root.qibla_direction
